/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Conexiones.SqlUsuarios;
import Conexiones.usuarios;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author Pc
 */
public class Registro extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtNomApe = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JLabel();
        Panel_Exit = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 800, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -10, -1, 143));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registro de Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 280, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo 1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Repita la contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 180, 40));

        txtCI.setForeground(new java.awt.Color(204, 204, 204));
        txtCI.setText(" Ingresa el documento de identidad");
        txtCI.setBorder(null);
        txtCI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCIMousePressed(evt);
            }
        });
        txtCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIActionPerformed(evt);
            }
        });
        jPanel1.add(txtCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 330, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 330, 10));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Documento de Indentidad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 220, 40));

        txtPassword2.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword2.setText("********");
        txtPassword2.setBorder(null);
        txtPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassword2MousePressed(evt);
            }
        });
        jPanel1.add(txtPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 330, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 330, 10));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 40));

        txtPassword1.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword1.setText("********");
        txtPassword1.setBorder(null);
        txtPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassword1MousePressed(evt);
            }
        });
        jPanel1.add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 330, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 330, 10));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setText("Nombre y apellido:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 170, 40));

        txtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefono.setText(" Ingresa tu numero telefonico");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 330, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 330, 10));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setText("Telefono:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 90, 40));

        txtNombreUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreUsuario.setText(" Ingrese el nombre de usuario");
        txtNombreUsuario.setBorder(null);
        txtNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMousePressed(evt);
            }
        });
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 330, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 330, 10));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setText("Nombre de Usuario:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, 40));

        txtNomApe.setForeground(new java.awt.Color(204, 204, 204));
        txtNomApe.setText(" Ingresa el nombre y apellido");
        txtNomApe.setBorder(null);
        txtNomApe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNomApeMousePressed(evt);
            }
        });
        txtNomApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomApeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 330, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 330, 10));

        jPanel2.setBackground(new java.awt.Color(31, 134, 195));

        btnAceptar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptar.setText("Aceptar");
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 110, 40));

        jPanel3.setBackground(new java.awt.Color(31, 134, 195));

        btnRegresar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegresar.setText("Regresar");
        btnRegresar.setToolTipText("");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 570));

        Panel_Exit.setBackground(new java.awt.Color(204, 204, 204));
        Panel_Exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_ExitMouseDragged(evt);
            }
        });
        Panel_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_ExitMousePressed(evt);
            }
        });
        Panel_Exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setText("X");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        Panel_Exit.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 0, 36, 30));

        getContentPane().add(Panel_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setForeground(Color.red);

    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setForeground(Color.BLACK);
    }//GEN-LAST:event_SalirMouseExited

    private void Panel_ExitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ExitMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Panel_ExitMouseDragged

    private void Panel_ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ExitMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Panel_ExitMousePressed

    private void txtCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCIActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        //
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtNomApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomApeActionPerformed

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        SqlUsuarios modSql = new SqlUsuarios();
        usuarios mod = new usuarios();
        String pass = new String(txtPassword1.getPassword());
        String passCon = new String(txtPassword2.getPassword());

        if (pass.equals(passCon)) {

            if (modSql.existeUsuario(txtNombreUsuario.getText()) == 0) {

                mod.setNombreUsuario(txtNombreUsuario.getText());
                mod.setPassword(passCon);
                mod.setCI(txtCI.getText());
                mod.setNomApe(txtNomApe.getText());
                mod.setTelefono(txtTelefono.getText());

                if (modSql.registrar(mod)) {
                    JOptionPane.showMessageDialog(null, "Se ha registrado exitosamente");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El Usuario ya existe");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El Password no coincide");
        }
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void limpiar() {
        txtNombreUsuario.setText("");
        txtPassword1.setText("");
        txtPassword2.setText("");
        txtCI.setText("");
        txtNomApe.setText("");
        txtTelefono.setText("");
    }
    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        btnAceptar.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        btnAceptar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAceptarMouseExited

    private void txtNombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMousePressed

        if (txtNombreUsuario.getText().equals(" Ingrese el nombre de usuario")) {
            txtNombreUsuario.setText("");
            txtNombreUsuario.setForeground(Color.black);
        }
        if (String.valueOf(txtPassword1.getPassword()).isEmpty()) {
            txtPassword1.setText("********");
            txtPassword1.setForeground(Color.gray);
        }
        if (String.valueOf(txtPassword2.getPassword()).isEmpty()) {
            txtPassword2.setText("********");
            txtPassword2.setForeground(Color.gray);
        }
        if (txtCI.getText().isEmpty()) {
            txtCI.setText(" Ingresa el documendo de indentidad");
            txtCI.setForeground(Color.gray);
        }
        if (txtNomApe.getText().isEmpty()) {
            txtNomApe.setText(" Ingresa el nombre y apellido");
            txtNomApe.setForeground(Color.gray);
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText(" Ingresa tu numero telefonico");
            txtTelefono.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreUsuarioMousePressed

    private void txtPassword1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassword1MousePressed
        if (txtNombreUsuario.getText().isEmpty()) {
            txtNombreUsuario.setText(" Ingrese el nombre de usuario");
            txtNombreUsuario.setForeground(Color.gray);
        }
        if (String.valueOf(txtPassword1.getPassword()).equals("********")) {
            txtPassword1.setText("");
            txtPassword1.setForeground(Color.black);
        }
        if (String.valueOf(txtPassword2.getPassword()).isEmpty()) {
            txtPassword2.setText("********");
            txtPassword2.setForeground(Color.gray);
        }
        if (txtCI.getText().isEmpty()) {
            txtCI.setText(" Ingresa el documento de identidad");
            txtCI.setForeground(Color.gray);
        }
        if (txtNomApe.getText().isEmpty()) {
            txtNomApe.setText(" Ingresa el nombre y apellido");
            txtNomApe.setForeground(Color.gray);
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText(" Ingresa tu numero telefonico");
            txtTelefono.setForeground(Color.gray);
        }

    }//GEN-LAST:event_txtPassword1MousePressed

    private void txtPassword2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassword2MousePressed
    if (txtNombreUsuario.getText().isEmpty()) {
        txtNombreUsuario.setText(" Ingrese el nombre de usuario");
        txtNombreUsuario.setForeground(Color.gray);
    }
    if (String.valueOf(txtPassword1.getPassword()).isEmpty()) {
        txtPassword1.setText("********");
        txtPassword1.setForeground(Color.gray);
    }
    if (String.valueOf(txtPassword2.getPassword()).equals("********")) {
        txtPassword2.setText("");
        txtPassword2.setForeground(Color.black);
    }
    if (txtCI.getText().isEmpty()) {
        txtCI.setText(" Ingresa el documento de identidad");
        txtCI.setForeground(Color.gray);
    }
    if (txtNomApe.getText().isEmpty()) {
        txtNomApe.setText(" Ingresa el nombre y apellido");
        txtNomApe.setForeground(Color.gray);
    }
    if (txtTelefono.getText().isEmpty()) {
        txtTelefono.setText(" Ingresa tu numero telefonico");
        txtTelefono.setForeground(Color.gray);
    }
    }//GEN-LAST:event_txtPassword2MousePressed

    private void txtCIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCIMousePressed
    if (txtNombreUsuario.getText().isEmpty()) {
        txtNombreUsuario.setText(" Ingrese el nombre de usuario");
        txtNombreUsuario.setForeground(Color.gray);
    }
    if (String.valueOf(txtPassword1.getPassword()).isEmpty()) {
        txtPassword1.setText("********");
        txtPassword1.setForeground(Color.gray);
    }
    if (String.valueOf(txtPassword2.getPassword()).isEmpty()) {
        txtPassword2.setText("********");
        txtPassword2.setForeground(Color.gray);
    }
    if (txtCI.getText().equals(" Ingresa el documento de identidad")) {
        txtCI.setText("");
        txtCI.setForeground(Color.black);
    }
    if (txtNomApe.getText().isEmpty()) {
        txtNomApe.setText(" Ingresa el nombre y apellido");
        txtNomApe.setForeground(Color.gray);
    }
    if (txtTelefono.getText().isEmpty()) {
        txtTelefono.setText(" Ingresa tu numero telefonico");
        txtTelefono.setForeground(Color.gray);
    }
    }//GEN-LAST:event_txtCIMousePressed

    private void txtNomApeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomApeMousePressed
   if (txtNombreUsuario.getText().isEmpty()) {
        txtNombreUsuario.setText(" Ingrese el nombre de usuario");
        txtNombreUsuario.setForeground(Color.gray);
    }
    if (String.valueOf(txtPassword1.getPassword()).isEmpty()) {
        txtPassword1.setText("********");
        txtPassword1.setForeground(Color.gray);
    }
    if (String.valueOf(txtPassword2.getPassword()).isEmpty()) {
        txtPassword2.setText("********");
        txtPassword2.setForeground(Color.gray);
    }
    if (txtCI.getText().isEmpty()) {
        txtCI.setText(" Ingresa el documento de identidad");
        txtCI.setForeground(Color.gray);
    }
    if (txtNomApe.getText().equals(" Ingresa el nombre y apellido")) {
        txtNomApe.setText("");
        txtNomApe.setForeground(Color.black);
    }
    if (txtTelefono.getText().isEmpty()) {
        txtTelefono.setText(" Ingresa tu numero telefonico");
        txtTelefono.setForeground(Color.gray);
    }
    }//GEN-LAST:event_txtNomApeMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
    if (txtNombreUsuario.getText().isEmpty()) {
        txtNombreUsuario.setText(" Ingrese el nombre de usuario");
        txtNombreUsuario.setForeground(Color.gray);
    }
    if (String.valueOf(txtPassword1.getPassword()).isEmpty()) {
        txtPassword1.setText("********");
        txtPassword1.setForeground(Color.gray);
    }
    if (String.valueOf(txtPassword2.getPassword()).isEmpty()) {
        txtPassword2.setText("********");
        txtPassword2.setForeground(Color.gray);
    }
    if (txtCI.getText().isEmpty()) {
        txtCI.setText(" Ingresa el documento de identidad");
        txtCI.setForeground(Color.gray);
    }
    if (txtNomApe.getText().isEmpty()) {
        txtNomApe.setText(" Ingresa el nombre y apellido");
        txtNomApe.setForeground(Color.gray);
    }
    if (txtTelefono.getText().equals(" Ingresa tu numero telefonico")){
        txtTelefono.setText("");
        txtTelefono.setForeground(Color.black);
    }
    }//GEN-LAST:event_txtTelefonoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Exit;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtNomApe;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
